library(lfe)

setwd("/Volumes/ntu/研究/Master-Thesis---Political-Polarization-in-2016-US-Election/Data/Hate Crime/Regression/")
hatecrime <- fread("hatecrime_reg.csv")
hatecrime_racial <- fread("hatecrime_racial_reg.csv")

##All hatecrime
model_mean_diff <- lm(crime_rate ~ mean_diff + factor(candidate) + factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_mean_diff)
model_mean_diff <- lm(crime_rate ~ mean_diff + factor(candidate) + factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_mean_diff)

model_std <- felm(crime_rate ~ std + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_std)
model_std <- felm(crime_rate ~ std + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_std)

model_right_2_ratio <- felm(crime_rate ~ right_2std_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_right_2_ratio)
model_right_2_ratio <- felm(crime_rate ~ right_2std_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_right_2_ratio)
model_right_2_total <- felm(crime_rate ~ right_2std_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_right_2_total)
model_right_2 <- felm(crime_rate ~ right_2std_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_right_2_total)

model_right_1_ratio <- felm(crime_rate ~ right_1_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_right_1_ratio)
model_right_1_ratio <- felm(crime_rate ~ right_1_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_right_1_ratio)
model_right_1_total <- felm(crime_rate ~ right_1_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_right_1_total)
model_right_1_total <- felm(crime_rate ~ right_1_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_right_1_total)

model_right_5_ratio <- felm(crime_rate ~ right_5_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_right_5_ratio)
model_right_5_ratio <- felm(crime_rate ~ right_5_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_right_5_ratio)
model_right_5_total <- felm(crime_rate ~ right_5_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_right_5_total)
model_right_5_total <- felm(crime_rate ~ right_5_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_right_5_total)

model_right_10_ratio <- felm(crime_rate ~ right_10_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_right_10_ratio)
model_right_10_ratio <- felm(crime_rate ~ right_10_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_right_10_ratio)
model_right_10_total <- felm(crime_rate ~ right_10_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_right_10_total)
model_right_10_total <- felm(crime_rate ~ right_10_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_right_10_total)

model_2_total <- felm(crime_rate ~ extreme_2std_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_2_total)
model_2_total <- felm(crime_rate ~ extreme_2std_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_2_total)
model_2_ratio <- felm(crime_rate ~ extreme_2std_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_2_ratio)
model_2_ratio <- felm(crime_rate ~ extreme_2std_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_2_ratio)

model_1_ratio <- felm(crime_rate ~ extreme_1_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_1_ratio)
model_1_ratio <- felm(crime_rate ~ extreme_1_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_1_ratio)
model_1_total <- felm(crime_rate ~ extreme_1_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_1_total)
model_1_total <- felm(crime_rate ~ extreme_1_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_1_total)

model_5_ratio <- felm(crime_rate ~ extreme_5_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_5_ratio)
model_5_ratio <- felm(crime_rate ~ extreme_5_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_5_ratio)
model_5_total <- felm(crime_rate ~ extreme_5_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_5_total)
model_5_total <- felm(crime_rate ~ extreme_5_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_5_total)

model_10_ratio <- felm(crime_rate ~ extreme_10_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_10_ratio) ##P = 0.0538
model_10_ratio <- felm(crime_rate ~ extreme_10_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_10_ratio)
model_10_total <- felm(crime_rate ~ extreme_10_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime)
summary(model_10_total) ##P = 0.0693
model_10_total <- felm(crime_rate ~ extreme_10_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime)
summary(model_10_total)

##Racial hatecrime
model_mean_diff <- felm(crime_rate ~ mean_diff + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_mean_diff)
model_mean_diff <- felm(crime_rate ~ mean_diff + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_mean_diff)

model_std <- felm(crime_rate ~ std + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_std)
model_std <- felm(crime_rate ~ std + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_std)

model_right_2_ratio <- felm(crime_rate ~ right_2std_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_right_2_ratio)
model_right_2_ratio <- felm(crime_rate ~ right_2std_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_right_2_ratio)
model_right_2_total <- felm(crime_rate ~ right_2std_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_right_2_total)
model_right_2 <- felm(crime_rate ~ right_2std_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_right_2_total)

model_right_1_ratio <- felm(crime_rate ~ right_1_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_right_1_ratio)
model_right_1_ratio <- felm(crime_rate ~ right_1_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_right_1_ratio)
model_right_1_total <- felm(crime_rate ~ right_1_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_right_1_total)
model_right_1_total <- felm(crime_rate ~ right_1_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_right_1_total)

model_right_5_ratio <- felm(crime_rate ~ right_5_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_right_5_ratio)
model_right_5_ratio <- felm(crime_rate ~ right_5_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_right_5_ratio)
model_right_5_total <- felm(crime_rate ~ right_5_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_right_5_total)
model_right_5_total <- felm(crime_rate ~ right_5_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_right_5_total)

model_right_10_ratio <- felm(crime_rate ~ right_10_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_right_10_ratio)
model_right_10_ratio <- felm(crime_rate ~ right_10_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_right_10_ratio)
model_right_10_total <- felm(crime_rate ~ right_10_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_right_10_total)
model_right_10_total <- felm(crime_rate ~ right_10_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_right_10_total)

model_2_total <- felm(crime_rate ~ extreme_2std_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_2_total)
model_2_total <- felm(crime_rate ~ extreme_2std_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_2_total)
model_2_ratio <- felm(crime_rate ~ extreme_2std_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_2_ratio)
model_2_ratio <- felm(crime_rate ~ extreme_2std_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_2_ratio)

model_1_ratio <- felm(crime_rate ~ extreme_1_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_1_ratio)
model_1_ratio <- felm(crime_rate ~ extreme_1_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_1_ratio)
model_1_total <- felm(crime_rate ~ extreme_1_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_1_total)
model_1_total <- felm(crime_rate ~ extreme_1_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_1_total)

model_5_ratio <- felm(crime_rate ~ extreme_5_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_5_ratio)
model_5_ratio <- felm(crime_rate ~ extreme_5_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_5_ratio)
model_5_total <- felm(crime_rate ~ extreme_5_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_5_total)
model_5_total <- felm(crime_rate ~ extreme_5_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_5_total)

model_10_ratio <- felm(crime_rate ~ extreme_10_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_10_ratio)
model_10_ratio <- felm(crime_rate ~ extreme_10_ratio + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_10_ratio)
model_10_total <- felm(crime_rate ~ extreme_10_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(state_name) * factor(month_year), data = hatecrime_racial)
summary(model_10_total)
model_10_total <- felm(crime_rate ~ extreme_10_total + factor(candidate) | factor(state_name) + factor(year) + factor(month_year) + factor(year) * factor(state_name) + factor(year) * factor(month_year) + factor(state_name) * factor(month_year) + factor(state_name) * factor(month_year) * factor(year), data = hatecrime_racial)
summary(model_10_total)





